### PR TITLE
build: bump to python v3.6 and f-string things

### PR DESCRIPTION
**Pull request by dwightmulcahy**
Ok... I'm just a f-string junkie and python 3.5 is so 2015.

feel free to ignore this... ;)

### CODE REVIEW

**Comment by jsenin** [comment]
> This will break older machines right? For example I have many sites running on a box with only Python 3.5 installed and this would completely hose all my sites. :)
> 
> In general I think we should aim for backwards compatability with existing installs where possible.

Yes, previous Debian for instance ( Debian 9 - stretch  )

**Comment by rcarmo** [comment]
I’d rather not push the requirement to 3.6 just yet.... especially not when the only benefit is string formatting, and there are plenty of Raspberry Pis out there still on Debian 9.

**Comment by dwightmulcahy** [comment]
@chr15m @rcarmo note the last line of the comment `feel free to ignore this... ;)`... to be honest I had done all the changes and said to myself, "wait, what version did f-strings come in?".  Looked it up and v3.6.  ":(  Made the last change and pushed it.  

Closing this since I agree with you even before pushing it.

**Comment by chr15m** [comment]
@dwightmulcahy good to have this code in the repo as a reference, even as a closed PR.

**Pull request closed without merging**
