### PR TITLE
issues/236 -- address DeprecationWarning in `click`

### PR DESCRIPTION
**Pull request by clusterfudge**
In [`click==8.0.0`](https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-0), `MultiCommand.resultcallback` is renamed to `result_callback`, along with a deprecation warning. This change adopts the new naming convention.

### CODE REVIEW

**Comment by clusterfudge** [comment]
FYI @rcarmo

**Comment by rcarmo** [comment]
So we need to have another look at this then. Since we rely on OS packages for `piku`, we need to draw the line someplace and figure out if/when to upgrade... Will mull things over.

**Comment by chr15m** [comment]
Was thinking about this one and I wonder if we could keep it backwards compatible by doing something like:

```
rc = getattr(piku, "resultcallback") or getattr(piku.result_callback)

@rc
def ...
```

**Comment by clusterfudge** [comment]
Sorry about the long turn-around! I took @chr15m ' suggestion (slightly modified to avoid creating a new global variable), and it looks like it passes muster. Please take a look when you get a chance!

**Comment by chr15m** [comment]
@clusterfudge thanks for following this up. From the tests it looks like there is a bug which may be resolved by passing a default arg of `None` to the `getattr` calls.

**Comment by chr15m** [comment]
Sorry @clusterfudge the linter is being very strict. 😅

**Comment by clusterfudge** [comment]
Hmm, I'm actually having a problem fixing/reproducing this one!

From what I can tell from the report, the 3.8 build made it the farthest (to linter), and cancelled all the other jobs (3.9 before it started). The 3.8 job fails on a warning (trailing whitespace). So, I tried to reproduce locally:

Using pyenv, I've created a py3.8.12 virtualenv, and run a script containing the workflow steps for the linter task:
```shell
#!/usr/bin/bash -e 

pip install flake8
# stop the build if there are Python syntax errors or undefined names
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
# Notes:
# --exit-zero treats all errors as warnings, but we don't use it anymore
# Allow longer lines for inlining SSH entries and set a complexity threshold that will pass for now
# Ignore W605 (https://lintlyci.github.io/Flake8Rules/rules/W605.html) because
# flake8 does not understand escaping dots inside templates for nginx and SSH
# TODO: pare down complexity and line length as we shrink piku core
flake8 . --ignore=W605 --count --max-complexity=60 --max-line-length=255 --statistics
```

This produces no errors:
```shell
(piku) seanfitz@pook:~/development/piku (issues/236 %)$ ./flake.sh 
Looking in indexes: https://pypi.heare.io/simple/
Requirement already satisfied: flake8 in /home/seanfitz/.pyenv/versions/3.8.12/envs/piku/lib/python3.8/site-packages (5.0.4)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /home/seanfitz/.pyenv/versions/3.8.12/envs/piku/lib/python3.8/site-packages (from flake8) (0.7.0)
Requirement already satisfied: pycodestyle<2.10.0,>=2.9.0 in /home/seanfitz/.pyenv/versions/3.8.12/envs/piku/lib/python3.8/site-packages (from flake8) (2.9.1)
Requirement already satisfied: pyflakes<2.6.0,>=2.5.0 in /home/seanfitz/.pyenv/versions/3.8.12/envs/piku/lib/python3.8/site-packages (from flake8) (2.5.0)
WARNING: You are using pip version 21.1.1; however, version 22.3 is available.
You should consider upgrading via the '/home/seanfitz/.pyenv/versions/3.8.12/envs/piku/bin/python3.8 -m pip install --upgrade pip' command.
0
0

seanfitz@pook:~/development/piku (issues/236 %)$ pip freeze
flake8==5.0.4
mccabe==0.7.0
pycodestyle==2.9.1
pyflakes==2.5.0
```

Looking at the error from the remote linter itself:
```
./piku.py:497:106: W291 trailing whitespace
1     W291 trailing whitespace
```
I _believe_ this is indicating trailing whitespace on line 497 at column 106 -- 
https://github.com/clusterfudge/piku/blob/issues/236/piku.py#L497

That doesn't make a lot of sense, since that line doesn't have 106 columns.

In case I'm reading it wrong, line 106 also doesn't have 497 columns.
https://github.com/clusterfudge/piku/blob/issues/236/piku.py#L106

Thoughts on what I'm missing here?

**Comment by chr15m** [comment]
OK I figured it out. The whitespace is actually in a previous PR that went in after your fork. If you merge master into your branch it will show up. I'll fix it today.

**Comment by chr15m** [comment]
The tests all pass! @rcarmo this PR now LGTM but I'll wait a couple of days for your ack before merging.

**Review by chr15m — APPROVED** [review]
LGTM thanks!

**Comment by clusterfudge** [comment]
Ah, missed your :+1: , merged master in for good measure. Thanks for the help here!

**Comment by chr15m** [comment]
Merging this now, thanks!

**Pull request merged**
