### PR TITLE
PHP Support

### PR DESCRIPTION
**Pull request by EpicVoyage**
After checking this was the right direction to approach PHP support from (#368), this is a draft of my initial working code.

It needs:
- Proper timezone configuration
- Environment variable to extend php.ini
- Documentation or a playbook to install `uwsgi-plugin-php`.

For Consideration:
- Should this support [multiple PHP versions](https://uwsgi-docs.readthedocs.io/en/latest/PHP.html#multiple-php-versions)?
- Should this support [Composer](https://getcomposer.org/), or leave that to a [release worker](https://piku.github.io/configuration/procfile.html)?

Example PHP deployment app: [piku-php-example](https://github.com/EpicVoyage/piku-php-example)

### CODE REVIEW

**Comment by chr15m** [comment]
I reckon the MVP for getting this merged should be: 

- fix timezone thing
- basic documentation
- just using the OS php

The other stuff can be built on top in new PRs if needed, but getting those basic things working is enough to start.

PHP has a large user base so I think getting this basic implementation in there would be useful for a lot of people.

**Comment by EpicVoyage** [comment]
After reviewing options to keep this simple, this is where I have landed:
- No variable is needed for custom `php.ini` file as this file is automatically detected by uWSGI. It completely overrides global `php.ini` file, and different apps override their own settings.
- Timezone configuration was removed. It can be configured in custom `php.ini` or PHP app code.

We now have 2 working sample apps. Feel free to clone them for official support or to link to mine:
- [piku-php-example](https://github.com/EpicVoyage/piku-php-example)
- [piku-php-laravel](https://github.com/EpicVoyage/piku-php-laravel)

There is a related documentation pull request:
- piku/piku.github.io#3

**Comment by rcarmo** [comment]
This is looking good, but I don't have the bandwidth to test or review it (I went through all the other PRs today and they were largely one-liners, so I have to leave this one as is). @chr15m, feel free to weigh in and merge when it's done...

**Comment by chr15m** [comment]
Cool, will give it a proper test.

**Comment by chr15m** [comment]
Weirdly it appears the package `uwsgi-plugin-php` is only available in Ubuntu 20 and 24 (but not 22). This is a bit awkward but I guess the only thing to do is document it.

**Comment by EpicVoyage** [comment]
The exclusion of this package on Ubuntu 22 is wild. I added a note to piku/piku.github.io#3.

It appears that the `uwsgi-plugin-php` [was available at some point](https://linux-packages.com/ubuntu-jammy-jellyfish/package/uwsgi-plugin-php) for Ubuntu 22. The Ubuntu package tracker indicates [it comes straight from Debian](https://alioth-lists.debian.net/pipermail/pkg-uwsgi-devel/), which I believe would be bookworm/sid. The Debian [package tracker](https://tracker.debian.org/pkg/uwsgi-plugin-php) is not clear on why it was excluded except for a [possible reference](https://release.debian.org/britney/hints/elbrus) to `uwsgi` not being stable enough? I can not make much sense of this.

**Comment by rcarmo** [comment]
Debian has this thing where they will not bring back packages from `unstable` consistently, although `unstable` refers to the entire distro, the build steps or the packages themselves depending on context.

**Comment by chr15m** [comment]
Just tested and this works great, thanks @EpicVoyage. I'm going to make a tweak to warn the user if they try to deploy a php app and the php uwsgi plugin is missing.

**Pull request merged**
