### PR TITLE
Show a message when no apps installed

### PR DESCRIPTION
**Pull request by jsenin**
Shows "There is no application yet." when requesting apps

### CODE REVIEW

**Comment by chr15m** [comment]
"There are no applications deployed." might be better wording.

The only downside to these usability enhacements (including the asterisk for running apps thing) is they become less scriptable. For example using `piku apps` in a script becomes more difficult because you have to parse these special cases. Not sure if that's a big concern.

**Comment by dwightmulcahy** [comment]
@chr15m so this will remove `MYSTRING="*thisdeployedapp"; echo ${MYSTRING:1}` the first character from the string.  There are several ways to peel that onion though in bash.  Not sure that is a big concern IMHO.

**Comment by jsenin** [comment]
> "There are no applications deployed." might be better wording.
> 
> The only downside to these usability enhacements (including the asterisk for running apps thing) is they become less scriptable. For example using `piku apps` in a script becomes more difficult because you have to parse these special cases. Not sure if that's a big concern.

Yes, I also thought it might be less scriptable, but maybe can help returning an error code when no apps installed.
We can also consider separating the asterisk with a tab to filter easily with awk or using bash as @dwightmulcahy says

**Comment by chr15m** [comment]
Yep and we could always add hooks specifically for use in scripts. For example git does this. It has a nice readable output for branches, with asterisk for active branch, but there are ways to list branches that are more script friendly too.

**Comment by rcarmo** [comment]
I'm going to merge this, change the message and let you guys fine-tune the parsing ;)

**Pull request merged**
