### PR TITLE
Improve Ruby on Rails support

### PR DESCRIPTION
**Pull request by mlainez**
Ruby support is currently rather basic and was not working well for Ruby on Rails applications. This proposed PR proposes small changes to bring better support for Ruby on Rails apps.

### CODE REVIEW

**Comment by chr15m** [comment]
I'm in favour of merging this @rcarmo. I don't have a good way to test the Ruby stuff but it doesn't look like it will break existing deploys so I'm happy to go with the testing @mlainez has done.

**Comment by mlainez** [comment]
Hi @chr15m, I didn't find any test suite that I could complement with ruby related tests. If there is any, I'd be happy to complete it. I am also working on a playbook to install rbenv https://github.com/mlainez/piku-bootstrap/blob/ruby_rbenv_support/playbooks/ruby.yml but I'm not done yet.

The changes proposed are indeed the minimum to benefit from the full piku experience with ruby, especially since the reverse proxy didn't work for me with the current code for ruby apps since they were skipped for nginx config.

I also want to add that I'm only testing this in a local network, not with public domains. So my testing is not really complete either. But seeing ruby apps on piku were to my knowledge not working with nginx, the proposed changes do fix an existing issue.

FYI, I'm running piku on an original Pine A64+ running armbian at home and also testing on x86 virutal machines with virtualbox.

**Comment by rcarmo** [comment]
This looks OK. I can’t test the Ruby bits either, and hopefully will have time next weekend to have a better look (as well as the other stuff that’s been contributed.)

**Comment by rcarmo** [comment]
Many thanks!

**Pull request merged**
