### PR TITLE
doc: add badges to README

### PR DESCRIPTION
**Pull request by dwightmulcahy**
this is the start of adding badges to show the state and condition of the repo.

https://www.freecodecamp.org/news/how-to-use-badges-to-stop-feeling-like-a-noob-d4e6600d37d2/

### CODE REVIEW

**Comment by rcarmo** [comment]
Yay, the checks passed! :)

(And yes, testing on 4 Python versions is overkill... we’re going to discuss what else the checks need to do in #95)

**Comment by dwightmulcahy** [comment]
noice!  now to start adding tests... ;)

**Comment by dwightmulcahy** [comment]
added issue #144 for discussion

**Comment by jsenin** [comment]
> Yay, the checks passed! :)
> 
> (And yes, testing on 4 Python versions is overkill... we’re going to discuss what else the checks need to do in #95)

great !

**Comment by rcarmo** [comment]
Let me see if I can figure out how to get an Actions badge and merge that in...

**Comment by dwightmulcahy** [comment]
an interesting project for bunch'o'badges... https://github.com/badges/shields

**Comment by dwightmulcahy** [comment]
off the top of my head:
- code coverage
- pass/fail tests
- # open issues
- latest version
- pep8 code grade
- link to Justin Bieber newest single

_(just seeing if you are paying attention)_

**Comment by jsenin** [comment]
> off the top of my head:
> 
> * code coverage
> * pass/fail tests
> * number of open issues
> * latest version
> * pep8 code grade
> * link to Justin Bieber newest single
> 
> _(just seeing if you are paying attention)_

I'm agree except the link to Justin B.  :angry:

**Pull request merged**
