### PR TITLE
Add link to phoenix example

### PR DESCRIPTION
**Pull request by axelbdt**
Hi,
I tested deployment of an Elixir/Phoenix app a few months ago. Figured it could be added to the examples.
Feel free to clone the repo into the piku org and link to that if you prefer.
Cheers

### CODE REVIEW

**Comment by rcarmo** [comment]
Hi! Let me have a look and get back to you over the weekend - we’re doing something similar with regards to Ruby where we’re creating sample repos and giving collaborators maintainer access, that might also be the way here since we can’t possibly cover all the runtimes :)On 10 Feb 2023, at 09:29, Axel Baudot ***@***.***> wrote:﻿Hi,
I tested deployment of an Elixir/Phoenix app a few months ago. Figured it could be added to the examples.
Feel free to clone the repo into the piku org and link to that if you prefer.
Cheers



You can view, comment on, or merge this pull request online at:
  https://github.com/piku/piku/pull/268

Commit Summary

  7f26617  Add link to phoenix example


File Changes  (1 file)

  
    M
    examples/README.md
    (1)
  


Patch Links:

  https://github.com/piku/piku/pull/268.patch
  https://github.com/piku/piku/pull/268.diff

**Comment by rcarmo** [comment]
Bumping this to apologize - had a hectic few days, will come back to this.

**Comment by axelbdt** [comment]
There's no rush at all, no worries

**Comment by rcarmo** [comment]
Hi there! I've taken a look and created [a repo for this](https://github.com/piku/sample-phoenix-app) - you have maintainer access, so you can push a clone to it and keep it updated - (which is easier for everyone concerned). Do ping us if you need any Elixir-specific tweaks, although from your `release` worker I think you've figured out all that's needed :)

**Comment by rcarmo** [comment]
Also, I will be adding a nicer table to the README with all the examples - thanks to you and other folk, we now have quite the little menagerie, and people should know they exist :)

**Pull request merged**
