### PR TITLE
Piku cli command line reference

### PR DESCRIPTION
**Pull request by jsenin**

### CODE REVIEW

**Comment by chr15m** [comment]
@rcarmo @jsenin do you think it's wise to duplicate the output of a command? This seems verbose and redundant. Who will update these docs every time the API changes?

**Comment by mariusa** [comment]
As a newcomer, it's useful to have this overview, but indeed it would be hard to update, unless having a script to generate it.

**Comment by mariusa** [comment]
Actually, running piku with no options and seeing the list there is good enough for me. I wouldn't google to find a separate doc.

**Comment by rcarmo** [comment]
I’m going to close this since we’ve moved on. Thanks for the contribution regardless.

**Pull request closed without merging**
