### PR TITLE
Fix #346 remaining SyntaxWarning with raw string

### LINKED ISSUE #346: Python3.12(on Ubuntu 24.04) SyntaxWarning issues
I'm brand new to piku, and setting it up on on Ubuntu 24.04 LTS, which runs python 3.12 now(Python 3.12.3).

In Python3.12 deprecated escape sequence issues have been upgraded to SyntaxWarning
```
/home/piku/piku.py:110: SyntaxWarning: invalid escape sequence '\.'
  NGINX_COMMON_FRAGMENT = """
/home/piku/piku.py:216: SyntaxWarning: invalid escape sequence '\*'
  CRON_REGEXP = "^((?:(?:\*\/)?\d+)|\*) ((?:(?:\*\/)?\d+)|\*) ((?:(?:\*\/)?\d+)|\*) ((?:(?:\*\/)?\d+)|\*) ((?:(?:\*\/)?\d+)|\*) (.*)$"
/home/piku/piku.py:852: SyntaxWarning: invalid escape sequence '\.'
  env['PIKU_INTERNAL_NGINX_BLOCK_GIT'] = "" if env.get('NGINX_ALLOW_GIT_FOLDERS') else "location ~ /\.git { deny all; }"
```
It's been deprecated since Python 3.6:

> A backslash-character pair that is not a valid escape sequence now generates a [DeprecationWarning](https://docs.python.org/dev/library/exceptions.html#DeprecationWarning). Although this will eventually become a [SyntaxError](https://docs.python.org/dev/library/exceptions.html#SyntaxError), that will not be for several Python releases. (Contributed by Emanuel Barry in [bpo-27364](https://bugs.python.org/issue?@action=redirect&bpo=27364).)

- https://docs.python.org/dev/whatsnew/3.6.html#deprecated-python-behavior

### PR DESCRIPTION
**Pull request by chr15m**

### CODE REVIEW

**Comment by rcarmo** [comment]
Hmmm. I need to upgrade my servers (none of them show this yet), and we need to bump the minimal version requirement soon...

**Comment by chr15m** [comment]
@rcarmo see my comment above - not sure why the tests seem to be using python-3.8 instead of the OS default which is 3.12 on focal (I think).

**Comment by rcarmo** [comment]
Yeah, I just went and updated the full test matrix without pruning the non-applicable cases. I only have a few scattered half-hours now and then...

**Comment by chr15m** [comment]
All good I know you're super busy. Thanks for merging!

**Pull request merged**
